MONGODB_HOST: mongodb-{{ env }}.spdevhops.shop
REDIS_HOST: redis-{{ env }}.spdevhops.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.spdevhops.shop
CART_HOST: cart.backend-alb-{{ env }}.spdevhops.shop
MYSQL_HOST: mysql-{{ env }}.spdevhops.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.spdevhops.shop
USER_HOST: user.backend-alb-{{ env }}.spdevhops.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.spdevhops.shop
PAYMENT_HOST: payment.bakcend-alb-{{ env }}.spdevhops.shop